# Practical_6: Numpy

---

### Exercise 1:
Create a NumPy array of integers from 1 to 10.


In [1]:
# Exercise 1
import numpy as np

arr = np.arange(1, 11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]



---

### Exercise 2:
Create a 3x3 NumPy array filled with zeros.


In [2]:
# Exercise 2
zeros_arr = np.zeros((3, 3))
print(zeros_arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]



---

### Exercise 3:
Create a NumPy array of 10 evenly spaced numbers between 0 and 5.


In [3]:
# Exercise 3
evenly_spaced = np.linspace(0, 5, 10)
print(evenly_spaced)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]



---

### Exercise 4:
Create a 5x5 identity matrix using NumPy.


In [4]:
# Exercise 4
identity_matrix = np.identity(5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]



---

### Exercise 5:
Create a 4x4 matrix with random values between 0 and 1.


In [5]:
# Exercise 5
random_matrix = np.random.rand(4, 4)
print(random_matrix)

[[0.48960872 0.9487375  0.65988001 0.19138307]
 [0.11740967 0.43277702 0.66140687 0.10335818]
 [0.0027299  0.94080894 0.51107751 0.61387915]
 [0.93467128 0.22601243 0.61627586 0.59690977]]



---

### Exercise 6:
Find the shape of a NumPy array.


In [6]:
# Exercise 6
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)

(2, 3)



---

### Exercise 7:
Reshape a 1D NumPy array of 16 elements into a 4x4 matrix.


In [7]:
# Exercise 7
arr = np.arange(16)
reshaped_arr = arr.reshape(4, 4)
print(reshaped_arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]



---

### Exercise 8:
Find the data type of the elements in a NumPy array.


In [8]:
# Exercise 8
arr = np.array([1, 2, 3])
print(arr.dtype)

int32



---

### Exercise 9:
Create a NumPy array of integers from 1 to 100 and find all even numbers in the array.


In [9]:
# Exercise 9
arr = np.arange(1, 101)
even_numbers = arr[arr % 2 == 0]
print(even_numbers)

[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100]



---

### Exercise 10:
Generate a 6x6 matrix of random integers between 10 and 50.


In [10]:
# Exercise 10
random_integers = np.random.randint(10, 51, size=(6, 6))
print(random_integers)

[[18 42 28 24 42 27]
 [50 29 22 19 23 13]
 [11 11 15 10 49 11]
 [33 27 40 25 24 38]
 [19 29 42 30 20 34]
 [16 10 45 29 38 12]]



---

### Exercise 11:
Slice a 2D NumPy array to extract a submatrix.


In [11]:
# Exercise 11
arr = np.array([[1, 2, 3], 
                [4, 5, 6], 
                [7, 8, 9]])

# Extract the top-left 2x2 submatrix
submatrix = arr[:2, :2]
print(submatrix)

[[1 2]
 [4 5]]



---

### Exercise 12:
Calculate the sum of all elements in a NumPy array.


In [12]:
# Exercise 12
arr = np.array([1, 2, 3, 4, 5])
total_sum = np.sum(arr)
print(total_sum)

15



---

### Exercise 13:
Calculate the mean, median, and standard deviation of a NumPy array.


In [13]:
# Exercise 13
arr = np.array([1, 2, 3, 4, 5])
mean = np.mean(arr)
median = np.median(arr)
std_dev = np.std(arr)

print("Mean:", mean)
print("Median:", median)
print("Standard Deviation:", std_dev)

Mean: 3.0
Median: 3.0
Standard Deviation: 1.4142135623730951



---

### Exercise 14:
Find the maximum and minimum values in a NumPy array.


In [14]:
# Exercise 14
arr = np.array([4, 2, 7, 1, 9])
max_val = np.max(arr)
min_val = np.min(arr)

print("Max:", max_val)
print("Min:", min_val)

Max: 9
Min: 1



---

### Exercise 15:
Create a NumPy array of 20 random integers and find the index of the maximum value.


In [15]:
# Exercise 15
arr = np.random.randint(1, 100, size=20)
max_index = np.argmax(arr)

print("Array:", arr)
print("Index of max value:", max_index)

Array: [66 60 69 80 55 98 82  3 81 99 33 67 70 20 91 22 37 37 94 37]
Index of max value: 9



---

### Exercise 16:
Create a NumPy array and reverse its elements.


In [16]:
# Exercise 16
arr = np.array([1, 2, 3, 4, 5])
reversed_arr = arr[::-1]
print(reversed_arr)

[5 4 3 2 1]



---

### Exercise 17:
Create a 3x3 matrix and multiply it element-wise by another 3x3 matrix.


In [17]:
# Exercise 17
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

b = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

result = a * b  # Element-wise multiplication
print(result)

[[ 9 16 21]
 [24 25 24]
 [21 16  9]]



---

### Exercise 18:
Create a diagonal matrix from a given 1D array.


In [18]:
# Exercise 18
arr = np.array([10, 20, 30, 40])
diagonal_matrix = np.diag(arr)
print(diagonal_matrix)

[[10  0  0  0]
 [ 0 20  0  0]
 [ 0  0 30  0]
 [ 0  0  0 40]]



---

### Exercise 19:
Perform matrix multiplication on two 2D NumPy arrays.


In [19]:
# Exercise 19
a = np.array([[1, 2],
              [3, 4]])

b = np.array([[5, 6],
              [7, 8]])

product = np.dot(a, b)
print(product)

[[19 22]
 [43 50]]



---

### Exercise 20:
Flatten a 2D NumPy array into a 1D array.


In [20]:
# Exercise 20
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

flattened = arr.flatten()
print(flattened)

[1 2 3 4 5 6]



---

### Exercise 21:
Stack two NumPy arrays vertically.


In [21]:
# Exercise 21
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

vertical_stack = np.vstack((a, b))
print(vertical_stack)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]



---

### Exercise 22:
Stack two NumPy arrays horizontally.


In [22]:
# Exercise 22
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

horizontal_stack = np.hstack((a, b))
print(horizontal_stack)

[[1 2 5 6]
 [3 4 7 8]]



---

### Exercise 23:
Split a NumPy array into multiple sub-arrays.


In [23]:
# Exercise 23
arr = np.array([1, 2, 3, 4, 5, 6])
split_arr = np.split(arr, 3)  # Split into 3 equal parts
print(split_arr)

[array([1, 2]), array([3, 4]), array([5, 6])]



---

### Exercise 24:
Generate a random NumPy array and round each element to two decimal places.


In [24]:
# Exercise 24
arr = np.random.rand(3, 3)
rounded_arr = np.round(arr, 2)
print(rounded_arr)

[[0.21 0.27 0.01]
 [0.17 0.97 0.61]
 [0.76 0.67 0.86]]



---

### Exercise 25:
Find the unique elements of a NumPy array.


In [25]:
# Exercise 25
arr = np.array([1, 2, 2, 3, 4, 4, 5])
unique_elements = np.unique(arr)
print(unique_elements)

[1 2 3 4 5]



---

### Exercise 26:
Replace all elements in a NumPy array that are less than a specific value with that value.


In [26]:
# Exercise 26
arr = np.array([1, 5, 8, 3, 0])
arr[arr < 4] = 4
print(arr)

[4 5 8 4 4]



---

### Exercise 27:
Find the cumulative sum of the elements in a NumPy array.


In [27]:
# Exercise 27
arr = np.array([1, 2, 3, 4])
cumsum = np.cumsum(arr)
print(cumsum)

[ 1  3  6 10]



---

### Exercise 28:
Create a NumPy array and find the number of non-zero elements in it.


In [28]:
# Exercise 28
arr = np.array([0, 1, 2, 0, 3, 0, 4])
non_zero_count = np.count_nonzero(arr)
print(non_zero_count)

4



---

### Exercise 29:
Create a NumPy array of random integers and sort it in ascending order.


In [29]:
# Exercise 29
arr = np.random.randint(1, 100, size=10)
sorted_arr = np.sort(arr)
print("Original:", arr)
print("Sorted:", sorted_arr)

Original: [38 15 83 65 56  6 28  6 33 53]
Sorted: [ 6  6 15 28 33 38 53 56 65 83]



---

### Exercise 30:
Find the row-wise and column-wise sum of a 3x3 matrix.


In [30]:
# Exercise 30
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

row_sum = np.sum(matrix, axis=1)
col_sum = np.sum(matrix, axis=0)

print("Row-wise sum:", row_sum)
print("Column-wise sum:", col_sum)

Row-wise sum: [ 6 15 24]
Column-wise sum: [12 15 18]



---

### Exercise 31:
Generate a 2D NumPy array with random values and normalize it (scale the values between 0 and 1).


In [31]:
# Exercise 31
arr = np.random.rand(3, 3)
normalized = (arr - arr.min()) / (arr.max() - arr.min())
print(normalized)

[[0.30216497 0.         0.84893102]
 [0.65177859 0.00855065 0.7166036 ]
 [0.5191492  0.2077476  1.        ]]



---

### Exercise 32:
Create two NumPy arrays and find the dot product.


In [32]:
# Exercise 32
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
dot_product = np.dot(a, b)
print(dot_product)

32



---

### Exercise 33:
Find the trace of a square NumPy matrix.


In [33]:
# Exercise 33
matrix = np.array([[1, 2], 
                   [3, 4]])
trace = np.trace(matrix)
print(trace)

5



---

### Exercise 34:
Create a 2D array and swap two rows.


In [34]:
# Exercise 34
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

arr[[0, 2]] = arr[[2, 0]]   
print(arr)

[[7 8 9]
 [4 5 6]
 [1 2 3]]



---

### Exercise 35:
Create a 1D NumPy array and convert it into a column vector.


In [35]:
# Exercise 35
arr = np.array([1, 2, 3, 4])
column_vector = arr.reshape(-1, 1)
print(column_vector)

[[1]
 [2]
 [3]
 [4]]



---

### Exercise 36:
Find the determinant of a 3x3 matrix.


In [36]:
# Exercise 36
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

determinant = np.linalg.det(matrix)
print(determinant)

-9.51619735392994e-16



---

### Exercise 37:
Find the eigenvalues and eigenvectors of a 2x2 matrix.


In [37]:
# Exercise 37
matrix = np.array([[2, 0],
                   [0, 3]])

eigenvalues, eigenvectors = np.linalg.eig(matrix)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

Eigenvalues: [2. 3.]
Eigenvectors:
 [[1. 0.]
 [0. 1.]]



---

### Exercise 38:
Solve a system of linear equations using NumPy.


In [38]:
# Exercise 38
A = np.array([[2, 3],
              [3, 4]])
B = np.array([8, 11])

solution = np.linalg.solve(A, B)
print("Solution:", solution)

Solution: [1. 2.]



---

### Exercise 39:
Add Gaussian noise to a NumPy array.


In [39]:
# Exercise 39
arr = np.array([10, 20, 30, 40, 50])
noise = np.random.normal(0, 1, arr.shape)
noisy_arr = arr + noise
print(noisy_arr)

[10.76666824 20.12508062 28.85952424 40.446359   49.83812813]



---

### Exercise 40:
Create a 4x4 matrix and extract the diagonal elements.


In [40]:
# Exercise 40
matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12],
                   [13, 14, 15, 16]])

diagonal = np.diag(matrix)
print(diagonal)

[ 1  6 11 16]



---

### Exercise 41:
Generate a NumPy array of 100 random values and clip the values to a range between 10 and 50.


In [41]:
# Exercise 41
arr = np.random.randint(0, 100, size=100)
clipped = np.clip(arr, 10, 50)
print(clipped)

[50 50 50 50 10 50 22 10 46 35 35 50 10 25 50 10 50 50 50 36 15 47 22 33
 40 35 35 50 50 50 50 50 26 10 36 50 50 48 50 29 50 50 28 50 50 50 10 50
 19 50 26 41 50 50 19 34 12 33 50 50 50 50 13 50 44 21 50 35 21 50 10 50
 50 48 26 50 10 50 31 50 10 50 15 50 50 35 50 14 43 50 19 18 40 41 50 10
 30 50 50 50]



---

### Exercise 42:
Create a 2D NumPy array and replace all negative values with zero.


In [42]:
# Exercise 42
arr = np.array([[1, -2, 3],
                [-4, 5, -6]])

arr[arr < 0] = 0
print(arr)

[[1 0 3]
 [0 5 0]]



---

### Exercise 43:
Find the inner and outer products of two NumPy arrays.


In [43]:
# Exercise 43
a = np.array([1, 2])
b = np.array([3, 4])

inner = np.inner(a, b)
outer = np.outer(a, b)

print("Inner product:", inner)
print("Outer product:\n", outer)

Inner product: 11
Outer product:
 [[3 4]
 [6 8]]



---

### Exercise 44:
Calculate the pairwise distances between points in a NumPy array.


In [44]:
# Exercise 44
from scipy.spatial import distance

points = np.array([[0, 0], [1, 0], [0, 1]])
dist_matrix = distance.cdist(points, points, 'euclidean')
print(dist_matrix)

[[0.         1.         1.        ]
 [1.         0.         1.41421356]
 [1.         1.41421356 0.        ]]



---

### Exercise 45:
Create a structured NumPy array with fields for `name`, `age`, and `height`.


In [45]:
# Exercise 45
data = np.array([('Alice', 25, 5.5), ('Bob', 30, 6.0)],
                dtype=[('name', 'U10'), ('age', 'i4'), ('height', 'f4')])

print(data)
print("Names:", data['name'])
print("Ages:", data['age'])

[('Alice', 25, 5.5) ('Bob', 30, 6. )]
Names: ['Alice' 'Bob']
Ages: [25 30]



---

### Exercise 46:
Create a 5x5 matrix of random integers and count the occurrences of each unique value.


In [46]:
# Exercise 46
arr = np.random.randint(0, 10, size=(5, 5))
unique, counts = np.unique(arr, return_counts=True)
print("Matrix:\n", arr)
print("Counts:", dict(zip(unique, counts)))

Matrix:
 [[0 9 8 2 4]
 [6 4 6 1 1]
 [5 4 3 4 6]
 [2 9 3 2 4]
 [0 0 7 4 4]]
Counts: {0: 3, 1: 2, 2: 3, 3: 2, 4: 7, 5: 1, 6: 3, 7: 1, 8: 1, 9: 2}



---

### Exercise 47:
Generate a random 3x3 NumPy array and subtract the mean of each row from the corresponding row.


In [47]:
# Exercise 47
arr = np.random.rand(3, 3)
row_mean = arr.mean(axis=1, keepdims=True)
adjusted = arr - row_mean
print(adjusted)

[[-0.22809948 -0.14109801  0.36919749]
 [ 0.50937098 -0.34905635 -0.16031464]
 [-0.10977908  0.14516805 -0.03538897]]



---

### Exercise 48:
Create a NumPy array of random integers and check if any of the values are greater than 50.


In [48]:
# Exercise 48
arr = np.random.randint(0, 100, size=10)
has_gt_50 = np.any(arr > 50)
print("Array:", arr)
print("Any > 50?", has_gt_50)

Array: [65 60  0 64 19 50 23 78 31 90]
Any > 50? True



---

### Exercise 49:
Calculate the moving average of a 1D NumPy array.


In [49]:
# Exercise 49
arr = np.array([1, 2, 3, 4, 5])
window_size = 3
moving_avg = np.convolve(arr, np.ones(window_size)/window_size, mode='valid')
print(moving_avg)

[2. 3. 4.]



---

### Exercise 50:
Find the Pearson correlation coefficient between two NumPy arrays.


In [50]:
# Exercise 50
x = np.array([1, 2, 3, 4, 5])
y = np.array([5, 4, 3, 2, 1])
corr = np.corrcoef(x, y)
print(corr)

[[ 1. -1.]
 [-1.  1.]]



---

### Exercise 51:
Convert a NumPy array of radians to degrees.


In [51]:
# Exercise 51
radians = np.array([0, np.pi/2, np.pi])
degrees = np.degrees(radians)
print(degrees)

[  0.  90. 180.]



---

### Exercise 52:
Create a random NumPy array and compute its variance and standard deviation.


In [52]:
# Exercise 52
arr = np.random.rand(10)
print("Variance:", np.var(arr))
print("Std Deviation:", np.std(arr))

Variance: 0.09403570208659304
Std Deviation: 0.3066524124910695



---

### Exercise 53:
Create a 2D NumPy array and find the indices of the maximum values along each axis.


In [53]:
# Exercise 53
arr = np.array([[1, 7, 3],
                [4, 5, 6]])

max_indices_rows = np.argmax(arr, axis=1)
max_indices_cols = np.argmax(arr, axis=0)

print("Max indices (rows):", max_indices_rows)
print("Max indices (cols):", max_indices_cols)

Max indices (rows): [1 2]
Max indices (cols): [1 0 1]



---

### Exercise 54:
Compute the inverse of a 2x2 NumPy matrix.


In [54]:
# Exercise 54
matrix = np.array([[4, 7],
                   [2, 6]])

inverse = np.linalg.inv(matrix)
print(inverse)

[[ 0.6 -0.7]
 [-0.2  0.4]]



---

### Exercise 55:
Create a NumPy array of 10 random values and standardize it (mean 0, variance 1).


In [55]:
# Exercise 55
arr = np.random.rand(10)
standardized = (arr - np.mean(arr)) / np.std(arr)
print(standardized)

[ 0.92005717  1.4172046  -0.31756639  0.8582454   1.43091518 -0.90368982
 -1.38244285 -0.40383047 -0.63800464 -0.98088818]



---

### Exercise 56:
Perform element-wise addition and subtraction on two NumPy arrays.


In [56]:
# Exercise 56
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

addition = a + b
subtraction = a - b

print("Addition:", addition)
print("Subtraction:", subtraction)

Addition: [5 7 9]
Subtraction: [-3 -3 -3]



---

### Exercise 57:
Create a NumPy array of random values and find the maximum element's index.


In [57]:
# Exercise 57
arr = np.random.rand(10)
max_index = np.argmax(arr)
print("Array:", arr)
print("Max index:", max_index)

Array: [0.43727986 0.41208932 0.94346765 0.40209338 0.02614983 0.13739055
 0.57652194 0.40621848 0.35324284 0.74179395]
Max index: 2



---

### Exercise 58:
Create a 3x3 NumPy array and rotate it by 90 degrees.


In [58]:
# Exercise 58
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

rotated = np.rot90(arr)
print(rotated)

[[3 6 9]
 [2 5 8]
 [1 4 7]]



---

### Exercise 59:
Compute the Frobenius norm of a matrix.


In [59]:
# Exercise 59
matrix = np.array([[1, 2],
                   [3, 4]])

norm = np.linalg.norm(matrix, 'fro')
print(norm)

5.477225575051661



---

### Exercise 60:
Create a 3D NumPy array and slice out a subarray.


In [60]:
# Exercise 60
arr = np.random.randint(0, 10, size=(3, 4, 5))
subarray = arr[0:2, 1:3, 2:5]
print(subarray)

[[[7 8 8]
  [9 2 8]]

 [[5 1 5]
  [4 6 2]]]



---